config/routes.rb
Bi::Application.routes.draw do
  root :to => 'home#index'

  resources :questions do
    member do
      get 'result'
      get 'download_result'
      post 'add_tag'
    end

    collection do
      get 'search'
    end
  end

  match 'questions/tags/:tag' => 'questions#tags', :as => 'question_tag'
  match 'kpis/tags/:tag' => 'kpis#tags', :as => 'kpi_tag'

  resources :kpis do
    member do
      post 'add_categorization'
      post 'add_tag'
    end
    collection do
      get 'stats'
      get 'search'
    end
  end

  resources :reports do
    collection do
    end
  end

  resources :visualizations, :only => :index
  match '/visualizations/:action', :controller => 'visualizations'
  match '/kpi_menu' => 'kpis#kpi_menu', :as => 'kpi_menu'
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :name, :description, :question_sql, :tag_list, :data_source
  attr_reader :error

  acts_as_taggable

  # If the sql query has names defined with 'as' then this will find all the columns in the query
  def fields
    question_sql
      .downcase
      .gsub(/(?<block>\((?:(?>[^()]+)|\g<block>)*\))/,'')  # remove nested blocks
      .split(/\s?select\s/).last.split('from').first       # take last root select statement
      .split(',')                                          # split select statement apart
      .map{ |e| (e.strip.ends_with? '%>') ?                # if ERB block...
        e.split[-2] :                                      # use block content. else...
        e.gsub('.', ' ').split[-1] }                       # take final token
  end

  # All ERB inputs of the format <%= input %>
  def inputs
    question_sql.split('<%=').drop(1).map{ |e| e.split[0] }.uniq
  end

  def perform(options = {})
    sql = build_sql(options)
    begin
      question_connection.execute(sql)
    rescue Exception => e
      @error = e
    end
  end

  def build_sql(options = {})
    Erubis::Eruby.new(self.question_sql).result(options)
  end

  def api_info
    {
      :name => name,
      :description => description,
      :inputs => inputs,
      :outputs => fields
    }
  end

  private
  def question_connection
    @question_connection || ConnectionChooser.new(data_source).connection
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @tags = Question.tag_counts_on(:tags)
    @questions = Question.order(:created_at).paginate(:page => params[:page])
  end

  def show
    @question = Question.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render :json => @question.api_info }
    end
  end

  def search
    @questions = Question.basic_search(params[:search][:search_term]).paginate(:page => params[:page])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(params[:question])
    if @question.save
      redirect_to question_path(@question)
    else
      redirect_to new_question_path
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update_attributes(params[:question])
      flash[:success] = "Question Updated"
      redirect_to question_path(@question)
    else
      render 'edit'
    end
  end

  def destroy
  end

  def tags
    @questions = Question.tagged_with(params[:tag]).paginate(:page => params[:page])
    @tag = params[:tag]
  end

  def add_tag
    @question = Question.find(params[:id])
    @tag = params[:tag]
    @question.tag_list.add(@tag)
    @question.save
  end

  def download_result
    @question = Question.find(params[:id])
    @result = @question.perform(params[:inputs])
    filename = "#{@question.name}_#{Time.now.strftime("%m_%d_%y")}.csv"
    answer = @result.to_csv_data.insert(0, "Question #{@question.id} - #{@question.name} - With Params #{params[:inputs].to_s.gsub(",","")}\n\n")
    send_data answer,
      :type => 'text/csv; charset=iso-8859-1; header=present',
      :disposition => "attachment; filename=#{filename}"
  end

  def result
    @inputs = params[:inputs]
    @question = Question.find(params[:id])
    @result = @question.perform(@inputs)
    @error = @question.error
    respond_to do |format|
      format.html
      format.json { render :json => @result }
    end
  end
end

app/views/questions/_question_fields.html.haml
= f.label :name, "Name"
= f.text_field :name
= f.label :description, "Description"
.question_description= f.text_area :description
= f.label :tag_list, "Tags (separated by commas)"
= f.text_field :tag_list
= f.label :data_source, "Data Source"
= f.select(:data_source, options_for_select(data_source_options, @question.data_source))
= f.label :question_sql
%p Add input fields to the question by including ERB variables such as <%= start_date %> in the SQL.
= f.text_area :question_sql, :class => "ace_text_area"
.row.ace_window
  .span12
    #editor
%br

app/views/questions/_question_list.html.haml
%ul.question_list
  - questions.each do |q|
    %li
      .row
        .span12
          = link_to q.name, question_path(q)
      .row.row_margin
        .span12
          = q.description

app/views/questions/_question_search_form.html.haml
= form_for :search, :url => search_questions_url, :method => :get do |f|
  = f.text_field :search_term
  %br
  = submit_tag('Search')

app/views/questions/_run_question_form.html.haml
= form_for :inputs, :url => result_question_url(question), :method => :get do |f|
  - question.inputs.each do |input|
    = input
    - if input.include?("date")
      = f.text_field input.to_sym, :class => "datepicker"
    - elsif input == 'group_by_range'
      = f.select(:group_by_range,
        options_for_select(['year', 'quarter', 'month', 'week', 'day']))
    - else
      = f.text_field input.to_sym
  %br
  = submit_tag('Get Result')

app/views/questions/add_tag.js.erb
$('ul.tags').append("<li class='tag'><a href='<%= question_tag_path(@tag) %>'><%= @tag %></a></li>");

app/views/questions/edit.html.haml
%h2 Edit Question

.row
  .span12
    = form_for @question, :url => question_url, :method => :put do |f|
      = render :partial => "question_fields", :locals => { :f => f }
      = f.submit "Save Question"

app/views/questions/index.html.haml
.row
  .span12
    %h3 Tags
  .span12
    = render index_tag_partial(Question, @tags)

.row
  .span12
    = render :partial => "question_search_form"
.row
  .span3
    %h3 Questions
  .span9.right_link
    = link_to "New Question", new_question_path

= render :partial => "question_list", :locals => { :questions => @questions }
= will_paginate @questions

app/views/questions/new.html.haml
%h2 New Question

= form_for @question, :url => questions_url, :method => :post do |f|
  = render :partial => "question_fields", :locals => { :f => f }
  %br
  = f.submit "Create Question"

app/views/questions/result.html.haml
.row
  .span8
    %h2 Result
  .span4.right_link
    = link_to "Back to Question", question_path(@question)

- if @error.present?
  .row
    .span12
      Error for
      = @question.name

  .row
    .span12
      = @error

- else
  = form_for :inputs, :url => download_result_question_url(@question), :method => :get do |f|
    - if @inputs.present?
      - @inputs.each do |input|
        = f.hidden_field input[0], :value => input[1]
    = submit_tag('Download CSV')

  .row
    .span12
      Result for
      = @question.name
      = "- #{@result.count} rows"

  .row
    .span12
      - if @result.count < 500
        #result_table
          = @result.to_html_table.html_safe
      - else
        This file has too many results to display. Please download the csv.

app/views/questions/search.html.haml
.row.row_margin_bottom
  .span3
    %h2 Questions
  .span9.right_link
    = link_to "New Question", new_question_path

.row
  .span12
    = render :partial => "question_search_form"

= render :partial => "question_list", :locals => { :questions => @questions }
= will_paginate @questions

app/views/questions/show.html.haml
.row
  .span6
    %h2= @question.name
    = link_to "Edit", edit_question_path(@question)
  .span6.right_link
    = link_to "Back to List", questions_path

.row
  .span12= render tag_partial(@question)

.row
  .span12
    %p
      %strong Name:
      = @question.name
    %p
      %strong Description:
      = @question.description

    %p
      %strong Inputs:
      = @question.inputs.join(", ")

    %p
      %strong Outputs:
      = @question.fields.join(", ")

    %p
      %strong Data Source:
      = @question.data_source

.row.row_margin
  .span12
    = render :partial => "run_question_form", :locals => { :question => @question }

app/views/questions/tags.html.haml
.row.row_margin_bottom
  .span3
    %h2 Questions
    .tag
      =link_to @tag, question_tag_path(@tag)
  .span9.right_link
    = link_to "New Question", new_question_path


= render :partial => "question_list", :locals => { :questions => @questions }
= will_paginate @questions