config/routes.rb
Bi::Application.routes.draw do
  root :to => 'home#index'

  resources :questions do
    member do
      get 'result'
      get 'download_result'
      post 'add_tag'
    end

    collection do
      get 'search'
    end
  end

  match 'questions/tags/:tag' => 'questions#tags', :as => 'question_tag'
  match 'kpis/tags/:tag' => 'kpis#tags', :as => 'kpi_tag'

  resources :kpis do
    member do
      post 'add_categorization'
      post 'add_tag'
    end
    collection do
      get 'stats'
      get 'search'
    end
  end

  resources :reports do
    collection do
    end
  end

  resources :visualizations, :only => :index
  match '/visualizations/:action', :controller => 'visualizations'
  match '/kpi_menu' => 'kpis#kpi_menu', :as => 'kpi_menu'
end

app/models/kpis/kpi.rb
class Kpi < ActiveRecord::Base
  attr_accessible :name, :query, :active, :tag_list, :data_source

  acts_as_taggable

  has_many :kpi_results, :dependent => :destroy

  scope :active, :conditions => {:active => true}

  def self.results_for_tag_and_date(tag, date)
    kpi_ids = Kpi.tagged_with(tag).map(&:id)
    KpiResult.scoped(:conditions => {:date => date, :kpi_id => kpi_ids})
  end

  def most_recent_result
    KpiResult.where("kpi_id = ?", self.id).order("date DESC").limit(1).first
  end

  def result_for_date(date)
    KpiResult.where("kpi_id = ? AND date = ?", self.id, date).first
  end

  def results_between_dates(start_date, end_date)
    KpiResult.where("kpi_id = ? AND date BETWEEN ? AND ?", self.id, start_date, end_date).order("date desc")
  end

  def values_between_dates(start_date, end_date, value)
    query = results_between_dates(start_date, end_date).select("date, max(#{value})").where("#{value} > 0").group(:date).to_sql
    connection.select_rows query
  end

  def calculate!(date)
    KpiCalculator.new(self, date).calculate!
  end

  def backfill(start = Date.new(2010,1,1), only_empty = true)
    date = start
    while date < Time.now.to_date do
      calculate(date) unless only_empty && result_for_date(date).present?
      date +=1
    end
  end

  def query_connection
    kpi_connection
  end

  private

  def kpi_connection
    if Rails.env != 'test'
      @connection ||= ConnectionChooser.new(data_source).connection
    end
  end

end

app/models/kpis/kpi_calculator.rb
# Responsible for calculating a kpi for a date
class KpiCalculator
  def initialize(kpi, date)
    @kpi = kpi
    @date = date
  end

  def current_result
    @kpi.result_for_date(@date)
  end

  def calculate!
    if current_result.nil?
      add_result!
    else
      recalculate_result!
    end
    save_percent_change!
  end

  def add_result!
    result = sql_result
    create_result!(result) unless result.nil?
  end

  def create_result!(result)
      KpiResult.create!({
        :date               => result["date"],
        :today              => result["today"],
        :t7days             => result["t7days"],
        :t30days            => result["t30days"],
        :qtd                => result["qtd"],
        :ytd                => result["ytd"],
        :kpi_id             => @kpi.id
      })
  end

  def sql_result
    @kpi.query_connection.execute(build_sql).first
  end

  def recalculate_result!
    kpi_result = sql_result
    current_result.update_attributes!(
      :today              => kpi_result["today"],
      :t7days             => kpi_result["t7days"],
      :t30days            => kpi_result["t30days"],
      :qtd                => kpi_result["qtd"],
      :ytd                => kpi_result["ytd"]
    ) unless kpi_result.nil?
  end

  def save_percent_change!
    result = current_result
    last_week = @kpi.result_for_date(@date - 7.days)
    last_month = @kpi.result_for_date(@date - 30.days)

    changes = percent_change_hash(result, last_week, last_month)
    result.update_attributes!(changes) unless result.nil?
  end

  def build_sql
    date = @date.strftime("%m/%d/%Y")

    kpi_date = Time.strptime(date,"%m/%d/%Y").strftime("%Y-%m-%d")
    end_date = Time.strptime(date,"%m/%d/%Y") + 1.days + 4.hours

    today_start      = end_date - 1.days
    seven_day_start  = end_date - 7.days
    thirty_day_start = end_date - 30.days
    quarter_start    = today_start.beginning_of_quarter + 4.hours
    year_start       = today_start.beginning_of_year + 4.hours
    start_date       = (year_start > thirty_day_start) ? thirty_day_start : year_start

    ERB.new(@kpi.query).result(binding)
  end

  private

  def percent_change_hash(result, last_week, last_month)
    return unless result.present?

    changes = {}
    changes.merge!(
      { :today_pct_change   => percent_change(result.today, last_week.today),
        :t7days_pct_change  => percent_change(result.t7days, last_week.t7days) }
    ) unless last_week.nil?

    changes.merge!(
      {:t30days_pct_change => percent_change(result.t30days, last_month.t30days)}
    ) unless last_month.nil?

    changes
  end

  def percent_change(new, old)
    return unless old.present? && new.present? && old != 0 && new != 0
    ((new / old.to_f - 1) * 100).round(2)
  end

end

app/models/kpis/kpi_daily_report.rb
class KpiDailyReport
  attr_accessor :tags, :date
  def initialize(date)
    @date = date
    @tags = ["Network", "Sales", "Sending", "Performance" ]
  end

  def results_for_tag(tag)
    Kpi.results_for_tag_and_date(tag, @date)
  end


end

app/models/kpis/kpi_result.rb
class KpiResult < ActiveRecord::Base
  attr_accessible :date, :name, :event_type, :partner, :today, :t7days, :t30days, :today_pct_change, :t7days_pct_change, :t30days_pct_change, :qtd, :ytd, :kpi_id

  belongs_to :kpi



  def humanize(column)
    val = self.send(column)
    return "?" unless val

    if column.to_s =~ /pct_change/
      "#{val.round(2)}%"
    elsif val.round == val
      val.round.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1,').reverse
    else
      val.round(2).to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1,').reverse
    end
  end

  def stat_increased?(stat)
    val = self.send(stat)
    val.present? && val > 0
  end

  def as_json(options = {})
    super(options).merge({'name' => kpi.name })
  end

end

app/models/kpis/kpi_runner.rb
class KpiRunner
  def initialize(date, rerun = false)
    @date = date
    @rerun = rerun
  end

  def run_kpis
    add_db_kpis
    add_performance_kpis
  end

  def add_performance_kpis
    PerformanceKpis.new.create_kpi_performance_results unless @rerun
  end

  def add_db_kpis
    Kpi.active.each do |k|
      begin
        start = Time.now
        print k.name
        k.calculate!(@date)
        print " - #{start - Time.now}\n"
      rescue
        print k.name
        print " - ERROR!!! -\n"
      end
    end
  end

  def deliver_daily_report
    KpiMailer.kpi_daily_report(@date).deliver
  end
end

app/controllers/kpis_controller.rb
class KpisController < ApplicationController
  skip_before_filter :require_user, :only => [:index, :show, :tags]

  def create
    last_run_hash = {:last_run => Time.now, :last_succeeded => Time.now - 1.year}
    @kpi = Kpi.new(params[:kpi].merge(last_run_hash))
    if @kpi.save
      flash[:success] = "Kpi Added"
      redirect_to kpi_path(@kpi)
    else
      redirect_to new_kpi_path
    end
  end

  def new
    @kpi = Kpi.new
  end

  def index
    @tags = Kpi.tag_counts_on(:tags)
    @kpis = Kpi.paginate(:page => params[:page])
  end

  def search
    @kpis = Kpi.basic_search(params[:search][:search_term]).paginate(:page => params[:page])
  end

  def show
    @kpi = Kpi.find(params[:id])
    @start_date = params[:start_date] || Time.now.weeks_ago(4).to_date
    @end_date = params[:end_date] || Time.now.yesterday.to_date
    @results = @kpi.results_between_dates(@start_date, @end_date)
    respond_to do |format|
      format.html
      format.json { render :json => @results }
    end
  end

  def edit
    @kpi = Kpi.find(params[:id])
  end

  def update
    @kpi = Kpi.find(params[:id])
    if @kpi.update_attributes(params[:kpi])
      flash[:success] = "Kpi updated"
      redirect_to kpi_path(@kpi)
    else
      render 'edit'
    end
  end

  def kpi_menu
  end

  def add_categorization
    @kpi = Kpi.find(params[:id])
    @category = KpiCategory.find_by_name(params[:category])
    KpiCategorization.create!(:kpi_id => @kpi.id, :kpi_category_id => @category.id, :name => @kpi.name, :sort_order => 1, :category => @category.name)
    redirect_to edit_kpi_path(@kpi)
  end

  def stats
    @date = params[:date].present? ? params[:date] : Time.now.yesterday.to_date
    @tag = params[:tag] || "Totals"
    @stats = Kpi.results_for_tag_and_date(@tag, @date)
    if @stats.count > 0
      @stats.sort_by!{|s| s.kpi.name }
    end
  end

  def destroy
  end


  def tags
    @kpis = Kpi.tagged_with(params[:tag]).paginate(:page => params[:page])
    @tag = params[:tag]
    respond_to do |format|
      format.html
      format.json { render :json => @kpis.map(&:most_recent_result) }
    end
  end

  def add_tag
    @kpi = Kpi.find(params[:id])
    @tag = params[:tag]
    @kpi.tag_list.add(@tag)
    @kpi.save
  end


end

app/views/kpis/_kpi_fields.html.haml
= f.label :name, "Name"
= f.text_field :name
= f.label :active, "Active"
= f.check_box :active
= f.label :data_source, "Data Source"
= f.select(:data_source, options_for_select(data_source_options, @kpi.data_source))
= f.label :query
= f.text_area :query, :class => "ace_text_area"
.row.ace_window
  .span12
    #editor
%br

app/views/kpis/_kpi_list.html.haml
%ul.kpi_list
  - kpis.each do |k|
    %li
      .row
        .span12
          = link_to k.name, kpi_path(k)

app/views/kpis/_kpi_search_form.html.haml
= form_for :search, :url => search_kpis_url, :method => :get do |f|
  = f.text_field :search_term
  %br
  = submit_tag('Search')

app/views/kpis/_kpi_table.html.haml
%table.kpi-table
  %thead
    %tr
      - if defined?(show_date)
        %th.first_col.right_border Date
      - else
        %th.first_col.right_border Name
      %th.graph_redraw{'data-field' => 'today'} Today
      %th.right_border.graph_redraw{'data-field' => 'today_pct_change'} % Change
      %th.graph_redraw{'data-field' => 't7days'} T7Days
      %th.right_border.graph_redraw{'data-field' => 't7days_pct_change'} % Change
      %th.graph_redraw{'data-field' => 't30days'} T30Days
      %th.right_border.graph_redraw{'data-field' => 't30days_pct_change'} % Change
      %th.right_border.graph_redraw{'data-field' => 'qtd'} QTD
      %th.right_border.graph_redraw{'data-field' => 'ytd'} YTD
  %tbody
    - stats.each do |stat|
      %tr{:class => cycle("alt", "")}
        %td.first_col.right_border
          - if defined?(show_date)
            = stat.date.strftime("%m-%d-%y")
          - else
            = link_to stat.kpi.name, kpi_path(stat.kpi)
        - ["today", "t7days", "t30days"].each do |window|
          %td.right_border
            = stat.humanize(window)
          %td.right_border
            - if stat.humanize("#{window}_pct_change").to_f > 0
              .pct_up
                = stat.humanize("#{window}_pct_change")
            - else
              .pct_down
                = stat.humanize("#{window}_pct_change")
        %td.right_border
          = stat.humanize(:qtd)
        %td.right_border
          = stat.humanize(:ytd)

app/views/kpis/add_tag.js.erb
$('ul.tags').append("<li class='tag'><a href='<%= kpi_tag_path(@tag) %>'><%= @tag %></a></li>");

app/views/kpis/edit.html.haml
%h2 Edit Kpi


.row
  .span12
    = form_for @kpi, :url => kpi_url, :method => :put do |f|
      = render :partial => "kpi_fields", :locals => { :f => f }
      = f.submit "Edit Kpi"

app/views/kpis/index.html.haml
.row
  .span3
    %h3 Kpis
  .span9.new_question_link
    = link_to "New Kpi", new_kpi_path
  .span12
    = render index_tag_partial(Kpi, @tags)

.row
  .span12
    = render :partial => "kpi_search_form"

= render :partial => "kpi_list", :locals => { :kpis => @kpis }
= will_paginate @kpis

app/views/kpis/new.html.haml
%h2 New Question

= form_for @kpi, :url => kpis_url, :method => :post do |f|
  = render :partial => "kpi_fields", :locals => { :f => f }
  %br
  = f.submit "Create Kpi"

app/views/kpis/search.html.haml
.row
  .span3
    %h3 Kpis
  .span9.new_question_link
    = link_to "New Kpi", new_kpi_path

.row
  .span12
    = render :partial => "kpi_search_form"

= render :partial => "kpi_list", :locals => { :kpis => @kpis }
= will_paginate @kpis

app/views/kpis/show.html.haml
.row
  .span12
    %h2=@kpi.name
    %strong Last Run:
    = @kpi.most_recent_result.date.strftime("%m/%d/%y")

.row
  .span12= render tag_partial(@kpi)

.row
  .span12
    = link_to "Edit", edit_kpi_path(@kpi)
    = form_tag kpi_path(@kpi), :method => :get do
      .row
        .span3
          = label_tag "Start Date"
          = text_field_tag('start_date', nil, :class => 'datepicker')
        .span6
          = label_tag "End Date"
          = text_field_tag('end_date', nil, :class => 'datepicker')
          = submit_tag "submit"

.row
  .span12
    %h3= "Results between #{@start_date} and #{@end_date}"

.row
  .span12
    #kpi_graph.graph

.row
  .span12
    = render "kpi_table", :stats => @results, :show_date => true

:javascript
  window.graph_data = #{@results.to_json};
  window.kpi_graph_name = "#{@kpi.name}";
  window.graph_description = {
    name: "kpi_graph"
  };

app/views/kpis/stats.html.haml
#kpi-stats
  %h2 Key Performance Indicators
  = link_to "Edit Kpis", kpis_path

  .kpi-view-options
    = form_tag request.path, :method => :get do
      .row
        .span4
          %label Daily summary for
          = select_tag(:tag, options_for_select(Kpi.tag_counts_on(:tags), params[:tag]))
        .span8
          %label on
          %input{:type => 'text', :class => 'clearable datepicker', :name => "date", :value => params[:date]}
          = submit_tag "View"

  %h3 #{@tag || 'Totals'} for #{@date.to_s}
  - if @stats && @stats.length > 0
    = render 'kpi_table', :stats => @stats
  - else
    %h4 Stats haven't been calculated for #{@date.to_s}

app/views/kpis/tags.html.haml
.row.row_margin_bottom
  .span3
    %h2 Questions
    .tag
      =link_to @tag, kpi_tag_path(@tag)
  .span9.right_link
    = link_to "New KPI", new_kpi_path


= render :partial => "kpi_list", :locals => { :kpis => @kpis }
= will_paginate @kpis